"""add unique constraint to stock symbol

Revision ID: 583abbebe85f
Revises: 60d21e30791b
Create Date: 2026-01-07 15:01:12.863944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583abbebe85f'
down_revision: Union[str, Sequence[str], None] = '60d21e30791b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    # ### end Alembic commands ###
