"""foreign key name for role and permission in user model corrected

Revision ID: 651e20411dcc
Revises: 15cfff76f6b3
Create Date: 2026-02-11 12:02:40.652369

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "651e20411dcc"
down_revision: Union[str, Sequence[str], None] = "15cfff76f6b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
